apiVersion: apps/v1
kind: Service
metadata:
  name: cocacola-backend-deployment
spec:
  type: NodePort
  selector:
    app: cocacola-backend
  ports:
  - protocol: TCP
    port: 8084
    nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocacola-backend-deployment
  labels:
    app: cocacola-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cocacola-backend
  template:
    metadata:
      labels:
        app: cocacola-backend
    spec:
      containers:
      - name: cocacola-backend
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
